<a href="https://colab.research.google.com/github/varshitha-123-tech/neural-networks/blob/main/Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a class Employee and then do the following


    • Create a data member to count the number of Employees
    • Create a constructor to initialize name, family, salary, department
    • Create a function to average salary
    • Create a Fulltime Employee class and it should inherit the properties of Employee class
    • Create the instances of Fulltime Employee class and Employee class and call their member functions.


In [ ]:
class Employee:

    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    @staticmethod
    def average_salary(employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees) if employees else 0

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

employee1 = Employee("Varshitha", "Kurra", 50000, "HR")
employee2 = Employee("Bhavna", "Miryala", 60000, "IT")
fulltime_employee1 = FulltimeEmployee("Amrutha", "Dama", 70000, "Finance")
fulltime_employee2 = FulltimeEmployee("Kalyani", "Hari", 80000, "Marketing")


In [ ]:
employees = [employee1, employee2, fulltime_employee1, fulltime_employee2]

In [ ]:
print(f"Total number of employees: {Employee.employee_count}")


Total number of employees: 4


In [ ]:
average_salary = Employee.average_salary(employees)
print(f"Average salary: {average_salary}")

Average salary: 65000.0


In [ ]:
for emp in employees:
    print(f"Name: {emp.name}, Family: {emp.family}, Salary: {emp.salary}, Department: {emp.department}")

Name: Varshitha, Family: Kurra, Salary: 50000, Department: HR
Name: Bhavna, Family: Miryala, Salary: 60000, Department: IT
Name: Amrutha, Family: Dama, Salary: 70000, Department: Finance
Name: Kalyani, Family: Hari, Salary: 80000, Department: Marketing


2. Numpy

Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)

(you can NOT implement it via for loop)



In [ ]:
import numpy as np

random_vector = np.random.uniform(1, 20, 20)

reshaped_array = random_vector.reshape(4, 5)

max_indices = np.argmax(reshaped_array, axis=1)
reshaped_array[np.arange(reshaped_array.shape[0]), max_indices] = 0

print("Reshaped Array with max replaced by 0:")
print(reshaped_array)


Reshaped Array with max replaced by 0:
[[11.43830989  3.4062202   0.          2.57609889  8.57316629]
 [12.59020507 15.68502638 15.3500335   3.44548019  0.        ]
 [ 0.          6.3154714   9.63041323  3.06938991  7.30421087]
 [10.40174281  8.09105227  4.40346159  0.         16.45065707]]


Video link:https://drive.google.com/file/d/1hdNmGMv6N1sbL_ByglKTsXl_H9sqipda/view?usp=drive_link

